# .streamlit/secrets.toml

# Add your Google Cloud Service Account JSON credentials here
# gcp_service_account = '''
# {
#   "type": "service_account",
#   "project_id": "your-project-id",
#   "private_key_id": "your-private-key-id",
#   "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n",
#   "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
#   "client_id": "your-client-id",
#   "auth_uri": "https://accounts.google.com/o/oauth2/auth",
#   "token_uri": "https://oauth2.googleapis.com/token",
#   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
#   "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project.iam.gserviceaccount.com",
#   "universe_domain": "googleapis.com"
# }
# '''

# Your actual Google Sheet URLs
[sheet_urls]
brand_health = "https://docs.google.com/spreadsheets/d/1A3zPpcEPuG3eiEaMiUNstwjKKaUG-zBxTXdcbsUSyu4/edit?gid=132659602#gid=132659602"
digital_presence = "https://docs.google.com/spreadsheets/d/1sf4WDYFJlpvVbQPEHSYHdKME6u8L2YyJGENiCJSYC7s/edit?gid=50487089#gid=50487089"
mql = "https://docs.google.com/spreadsheets/d/11P2DmsThZ9NfeLHFXXHAIpwF88fBPVCZeQttMBJVL3I/edit?gid=1745838439#gid=1745838439"
product_nps = "https://docs.google.com/spreadsheets/d/1FZwy4OP5gV7lkyWdAXwsQPVn20nC35MGk1QzJjjo5YU/edit?gid=158922633#gid=158922633"
partner_mentions = "https://docs.google.com/spreadsheets/d/12D2QjT_7pjSWhQxFNMXnktKVhAKQpnFpQx_pJBtaheM/edit?gid=1790899077#gid=1790899077"
partner_nps = "https://docs.google.com/spreadsheets/d/159xI3uXSjFgVZcwMH8zP32lZo9b3_Hk18oXS5D-sj0U/edit?gid=1770113333#gid=1770113333"
creator_nps = "https://docs.google.com/spreadsheets/d/1JVTTjHJmi51wquc5aWYEl2oPPVtpGqBTZYZHjzRICGo/edit?gid=1399491342#gid=1399491342"
innovation = "https://docs.google.com/spreadsheets/d/1pOTeJfZd4JYcNROtUacFLw-hsjHEiBfyHBZty-4Z88I/edit?gid=653256297#gid=653256297"
